### PR TITLE
Accessibility Priority Issues

### PR DESCRIPTION
**Pull request by emichaud998**
Pull requests into this repository require the following checks to be completed by the submitter and reviewers.

Changes in this PR:
First priority accessibility changes including:
- Removing the tab-index for the body of the webpage so they aren't highlighted
- Distinct styling for hovering and focusing on elements
- Added a skip link to allow users to skip over the menu straight to the content

**Submitter:**
- [x] Administrative tasks are complete.
  - This pull request describes why these changes were made.
  - The JIRA ticket links to this PR.
  - The JIRA ticket for this PR is: [Lantern 515 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-515)
- [x] Tests are complete.
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.
- [x] Code review has been performed.
  - Code diff has been done and checked to ensure only expected code is being committed.
  - A linter for the language has been run.

**Primary Reviewer:**

- [x] Code works.
  - Code has been run locally and the basic functionality affected by the PR has been checked.
  - Edge cases have been checked to ensure behavior is as expected.
- [x] Code review has been performed.
  - Code is maintainable, reusable, efficient, and correct.
  - Code accomplishes the tasks purpose.
  - Code follows style guidance appropriate for the language, including passing linter checks.
  - Code is well commented (which does not mean verbosely commented).
- [x] Tests are complete.
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.

**Merger:**

Prior to merging, ensure that all checks have been completed. Delete the branch after the merge
is complete.

### CODE REVIEW

**Comment by bmath10** [comment]
How do you open the modal for an endpoint?

**Comment by emichaud998** [comment]
> How do you open the modal for an endpoint?

It should now open on an Enter keypress!

**Comment by bmath10** [comment]
On the organizations page, I had to switch tabs using the arrow keys. If possible, it would be nice if that worked with tabbing like the tabs on the other pages.

**Comment by bmath10** [comment]
Would it be possible to have some sort of "Skip content" button for the FHIR Resource Types filter on the Resource Page? It just seems not ideal to have to tab through every resource twice to navigate the page...

**Comment by bmath10** [comment]
Something that I didn't think about is that you can't tab to the individual points on the map on the Location page. I think probably the easiest thing to do to make this accessible is to add a table under the map (or maybe next to?) with the endpoint URL, the organization name, and the zipcode. Then at least someone with a screen reader would have all of the data, even if it's not navigating the map. If you think that's a good idea, or have another alternative that you want to discuss, let me know and I can make a ticket to update that page!

**Comment by bmath10** [comment]
The Security and SMART Response pages are still showing the list of organizations incorrectly. Is that because the fix isn't merged into this branch, or does it need to be fixed again?

**Review by bmath10 — APPROVED** [review]

**Pull request merged**
