### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by edeyoung**
Dockerizes the capability querier and endpoint manager.

The capability querier is set to restart on fail. It fails if it cannot connect to rabbitmq. the capability querier automatically begins querying fhir api endpoints.

The endpoint manager does nothing when started at this point other than display a message.

To check:
* run `make run`
* check log messages to ensure that `endpoint_manager` starts as expected
* check log message to see that `capability_querier` probably has at least one failed start but should eventually be successful. You should see log INFO messages for every 10 messages added to a queue.
* check the rabbitmq site (localhost:15672) to see that messages are being added to the queue.

---

Pull requests into this repository require the following checks to be completed by the submitter and reviewers.

**Submitter:**
- [x] Administrative tasks are complete.
  - This pull request describes why these changes were made.
  - The JIRA ticket links to this PR.
  - The JIRA ticket for this PR is: https://oncprojectracking.healthit.gov/support/browse/LANTERN-121
  - vendor/ directories have been updated
    - New dependencies have been added
    - Local dependencies have been updated
- [x] Tests are complete. N/A
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.
- [x] Code review has been performed.
  - Code diff has been done and checked to ensure only expected code is being committed.
  - A linter for the language has been run.

**Primary Reviewer:**
@mayerm94
- [x] Code works.
  - Code has been run locally and the basic functionality affected by the PR has been checked.
  - Edge cases have been checked to ensure behavior is as expected.
- [x] Code review has been performed.
  - Code is maintainable, reusable, efficient, and correct.
  - Code accomplishes the tasks purpose.
  - Code follows style guidance appropriate for the language, including passing linter checks.
  - Code is well commented (which does not mean verbosely commented).
  - vendor/ directories have been updated
    - New dependencies have been added
    - Local dependencies have been updated
- [x] Tests are complete.
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.

**Secondary Reviewer:**

- [x] Code works.
  - Code has been run locally and the basic functionality affected by the PR has been checked.
  - Edge cases have been checked to ensure behavior is as expected.
- [x] Code review has been performed.
  - Code accomplishes the tasks purpose.
- [x] Tests are complete.
  - Tests have been run locally and pass.

**Merger:**

Prior to merging, ensure that all checks have been completed. Delete the branch after the merge is complete.

### CODE REVIEW

**Comment by bmath10** [comment]
Running the end-to-end test didn't seem to work. Before it quit I got:
```
endpoint_manager exited with code 0
Aborting on container exit...
```

**Comment by bmath10** [comment]
I used the rabbitmq site to see what the messages on the queue looked like using the "Get messages," and granted I've never used this before so I'm not sure how this works, but it looked like all of the messages had access errors with `x509: certificate signed by unknown authority`. This seems like it could be a docker certificate issue?

**Comment by edeyoung** [comment]
it's possible this is related to the transparent proxy move. @mayerm94 ?

**Comment by bmath10** [comment]
> Running the end-to-end test didn't seem to work. Before it quit I got:
> 
> ```
> endpoint_manager exited with code 0
> Aborting on container exit...
> ```

Resolved!

**Pull request merged**
