### PR TITLE
Smart equal ignore

### PR DESCRIPTION
**Pull request by emichaud998**
Changes in this PR:

Changed the SMART Response EqualIgnore function to receive a list of fields to ignore as a variable. Updated SMART Response EqualIgnore tests to make sure the function works as expected when given list of ignored fields.

Pull requests into this repository require the following checks to be completed by the submitter and reviewers.

**Submitter:**
- [x] Administrative tasks are complete.
  - This pull request describes why these changes were made.
  - The JIRA ticket links to this PR.
  - The JIRA ticket for this PR is: [Lantern 311 JIRA Ticket](https://oncprojectracking.healthit.gov/support/browse/LANTERN-311)
- [x] Tests are complete.
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.
- [x] Code review has been performed.
  - Code diff has been done and checked to ensure only expected code is being committed.
  - A linter for the language has been run.

**Primary Reviewer:**

- [x] Code works.
  - Code has been run locally and the basic functionality affected by the PR has been checked.
  - Edge cases have been checked to ensure behavior is as expected.
- [x] Code review has been performed.
  - Code is maintainable, reusable, efficient, and correct.
  - Code accomplishes the tasks purpose.
  - Code follows style guidance appropriate for the language, including passing linter checks.
  - Code is well commented (which does not mean verbosely commented).
- [x] Tests are complete.
  - Tests are included and test edge cases.
  - Tests have been run locally and pass.

**Secondary Reviewer:**

- [ ] Code works.
  - Code has been run locally and the basic functionality affected by the PR has been checked.
  - Edge cases have been checked to ensure behavior is as expected.
- [ ] Code review has been performed.
  - Code accomplishes the tasks purpose.
- [ ] Tests are complete.
  - Tests have been run locally and pass.

**Merger:**

Prior to merging, ensure that all checks have been completed. Delete the branch after the merge
is complete.

Create a new branch `<branch name>_gomodupdate`. Run `make update_mods` to update the `go.mod`
and `go.sum` files to point to master. Create a PR. Require one sanity check reviewer.

### CODE REVIEW

**Comment by bmath10** [comment]
This branch has that same small issue with shiny dashboard that the other smart response merge request had, so i assume it'll be resolved once you rebase this branch!

**Comment by mayerm94** [comment]
image
🤔  I'm getting this error when building and populating database from scratch.

**Comment by bmath10** [comment]
> image
> 🤔 I'm getting this error when building and populating database from scratch.

This is an error from the SMART Response branch, Emily addressed it in the other PR but this hasn't been updated with those changes yet!

**Comment by bmath10** [comment]
I know you didn't touch this but I figure it could be easily addressed in this PR since I just noticed it: I don't think the query for the FHIR Version/Capability/Endpoints table is correct. I think the `get_smart_response_capabilities` query in the `endpoints.R` should be formatted using LEFT JOINs like in the `get_well_known_endpoints_tbl` query right below it. Let me know if that doesn't work or you have any questions!

**Review by mayerm94 — APPROVED** [review]

**Pull request merged**
